name: LintTestDeployment
on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - develop
      - "dev-*" #this will allow these kind of branches --> dev-one dev-two etc
      - "dev-**" #this will allow these kind of branches --> dev-one-1 dev-one-2 dev-two-1 (multiple hypens)

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: download repo
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: running lint
        run: npm run lint
  test:
    runs-on: windows-latest
    needs: [lint]
    steps:
      - name: download repo
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: running test
        run: npm run test
      - name: build project
        run: npm run build
      - name: final build
        run: echo "all required pipeline completed"
  build:
    needs: [test]
    runs-on: windows-latest
    steps:
      - name: download repo
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path:
            | #Here dist is the folder which we need it can be file, folder, since dist2 is not available the job will not add in the dist-files, we can add package.json whatever we required
            dist 
            dist2
  deploy:
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: get artifcats from above job
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: output
        run: ls
      - name: deploy project
        run: echo "Deployed"
